---
- name: Run kolla-ansible prechecks
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible prechecks
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/deploy-prechecks 2>&1

- name: Run kolla-ansible pull
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible pull
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/pull 2>&1

- name: Run kolla-ansible deploy
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible deploy
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/deploy 2>&1

- name: Run kolla-ansible post-deploy
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible post-deploy
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/post-deploy 2>&1

- name: Run kolla-ansible validate-config on upgrades
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible validate-config
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/validate-config 2>&1
  when: not is_upgrade | bool

- name: Run kolla-ansible check
  ansible.builtin.shell:
    cmd: >
      . {{ kolla_ansible_venv_path }}/bin/activate &&
      kolla-ansible check
      -i /etc/kolla/inventory
      -vvv
      >/tmp/logs/ansible/check 2>&1
