---
- name: Ensure /etc/kolla is writable
  become: true
  ansible.builtin.file:
    path: /etc/kolla
    state: directory
    mode: "0777"
    recurse: true

- import_tasks: certificates.yml
- import_tasks: deploy.yml
